Bug/282 player join during selection phase
I3uckwheat/cards-of-carousal pull request #283
Opened 2021-05-01 18:18 UTC by fortypercenttitanium

#### 0. Make sure your issue is linked:

Close #282 

#### 1. Purpose:

Currently if a player joins mid-game while other players are selecting their cards, the game can get stuck waiting for the new player to submit cards they don't have. This fix will deal new cards to the new player and allow them to play right away, thus keeping the game moving.

#### 2. Implementation:

This one required a little bit of a rework in multiple areas:

### HostReducer
* PLAYER_CONNECTED
  * Check if the game state is waiting for players to submit cards
    * If so, deal cards again 
      * current players will still only have the cards they previously had, the new one will receive a full hand
    * If not, proceed as normal
  * Decouples clearing submitted cards from the `dealWhiteCards` function so we can retain which players have submitted cards
  * Imports hostReducerMiddleware to send the cards to the players again once they've been updated. This function is only a side effect and does not fallthrough to a dispatch, so it is a safe import.
    * When sending cards, implements a `newPlayer` property to indicate whether the cards are being dealt as a result of a new player joining. This ensures that the middleware sends the correct socket message to the players (see next).

### hostReducerMiddleware
* `sendCardsToPlayers`
  * When sending cards, implements a `shouldPreserveGameState` property to indicate whether the players receiving cards should be brought to the player-select screen. This boolean (calculated based on the new player's ID compared to the player receiving cards) ensures that players who have already submitted their cards aren't brought back to the selection screen.

### PlayerReducer
Looks to the payload to indicate whether the player's game state should change to 'player-select' (see above)

### HostScreenController
Removes a game state case that should not have been added to the host end. 

#### 3. Possible Issues:

Consider additional edge cases related to the game state and new players joining. Try joining with multiple players mid game.

#### 4. How to Test:

1. Pull branch
2. Run game, open 5+ tabs
3. Join with 3 players, start game, submit cards on one of the tabs
4. Join game with an additional player (or more).
5. Observe the game state of each player (and host), attempt to continue on with the game.

#### 5. Cleanup
- [x] I've added all TODOs needed
- [x] I've removed all unneeded comments
- [x] I've updated the snapshot tests and checked to make sure they're accurate if they changed
- [x] I've removed all unnecessary `console.log`s

2021-05-01 21:42 UTC, I3uckwheat submitted a review, later dismissed

2021-05-03 02:29 UTC, I3uckwheat requested changes

2021-05-03 14:00 UTC, pklepa reviewed
I tested this implementation in different scenarios: one person joining whilst on `waiting-to-receive-cards`, multiple people joining, a person joining whilst another leaves...

Although it seems to be solid and I didn't manage to reproduce the loop that Briggs mentioned, I do agree that moving the conditional (whether or not the game is running) and its subsequent side effects over to the event level in `HostContext` would be beneficial

2021-05-05 02:34 UTC, I3uckwheat requested changes

2021-05-06 20:18 UTC, I3uckwheat commented on frontend/src/components/PlayerList/PlayerList.js
> +  ];
This will show staged and in-play players, right?

2021-05-06 22:34 UTC, I3uckwheat commented on frontend/src/screenControllers/HostScreenController/HostScreenController.spec.js
> -
Even better

2021-05-06 22:44 UTC, I3uckwheat submitted a review, later dismissed

2021-05-06 22:49 UTC, pklepa submitted a review, later dismissed

2021-05-06 22:57 UTC, zachmmeyer approved these changes
Looks great. Tested with a bunch of new players while joining white card and czar selection. No crashing. Only had to update 1 test from the merge.

2021-05-06 23:00 UTC, I3uckwheat approved these changes

2021-05-06 23:38 UTC, merged