Feature/223 scoring feature
I3uckwheat/cards-of-carousal pull request #292
Opened 2021-05-05 23:49 UTC by pklepa

#### 0. Make sure your issue is linked:

Closes #223 

#### 1. Purpose:

Introduces the score tracking in order to progress with the game and provides a new Game-Over screen to signalize the game is over.

#### 2. Implementation:

Scores are added to the round winner as soon as it is submitted by the host in the `WINNER_SELECTED` event (which is the updated name for the late `SELECT_WINNER`). I created a distinction between `HostRoundWinnerScreen` and `HostGameWinnerScreen` to better represent the current game stage. `HostRoundWinnerScreen` is amended to check whether the `gameSettings.winningScore` is met and if so, a `GAME_OVER` event is dispatched to update the state to the next screen.

The Host is then sent to the new `HostGameWinnerScreen` whilst the players are sent a personalised message depending on whether they won or lost the game.

#### 3. Possible Issues:

This PR is put as a Draft because I didn't manage to finish the test suite for `HostGameWinnerScreen`. Also, I left an important TODO on said screen that states that the "Start new game" button should ideally reset the game to a blank state, but preserve players connections and game settings. This is quite a bit of work that needs attention to work properly but for now the button merely closes the lobby.

#### 4. How to Test:

1. Open multiple instances of the app (3 tabs minimum)
2. Host the game in one tab
3. Join as players with the rest
4. *Set Winning Score to 1*
5. Start the game
6. Play normally
7. See the game over screen as the winning score is met after one round

#### 5. Cleanup
- [x] I've added all TODOs needed
- [x] I've removed all unneeded comments
- [x] I've updated the snapshot tests and checked to make sure they're accurate if they changed
- [x] I've removed all unnecessary `console.log`s

2021-05-06 22:59 UTC, I3uckwheat requested changes

2021-05-06 22:59 UTC, I3uckwheat commented on frontend/src/screenControllers/PlayerScreenController/PlayerScreenController.js
> +    case 'showing-end-game-messages':
We should probably name this something other than "showing" as it doesn't fit with the rest. Maybe "end-game" or something?

2021-05-07 03:12 UTC, wise-king-sullyman commented on frontend/src/screens/HostGameOverScreen/HostGameOverScreen.spec.js
> +
Is there a particular reason that you test that the "start new game" button renders but not the "close game" button"?

2021-05-08 19:48 UTC, I3uckwheat approved these changes

2021-05-08 19:49 UTC, wise-king-sullyman approved these changes

2021-05-08 19:49 UTC, merged