Fullscreen
I3uckwheat/cards-of-carousal pull request #326
Opened 2021-06-08 17:22 UTC by fortypercenttitanium

#### 0. Make sure your issue is linked:

#### 1. Purpose:

Fullscreens the app for host and players

#### 2. Implementation:

Utilizes browser `requestFullscreen()` API.

#### 3. Possible Issues:

Needs testing on multiple browsers and devices.

#### 4. How to Test:

1. Edit `start.js` in the backend folder. The `app.listen` method needs a second argument, a string of '0.0.0.0' so the app is available on your local network:
```js
app.listen(process.env.EXPRESS_PORT, '0.0.0.0', () =>
  // eslint-disable-next-line no-console
  console.log(
    `Express listening at http://localhost:${process.env.EXPRESS_PORT}`,
  ),
);
```
2. Ensure all devices are on your local home network
3. Lookup the internal IP address of the computer running the app and write it down.
4. In frontend.env file, replace `localhost` with the IP address you just wrote down.
5. run `npm run dev:frontend` and `npm run dev:backend` in separate terminals 
6. On the host computer, you can use localhost just fine for the app, but on devices you are testing with, open the browser and navigate to `http://<HOST_COMPUTER_IP>:3000` (inside the angle brackets, replace the the text with the ip you wrote down earlier, and remove the angle brackets).
7. Host the game on one computer, join on any devices you want to test.
8. Click JOIN or HOST, and see if the game enters fullscreen mode.

#### 5. Cleanup
- [x] I've added all TODOs needed
- [x] I've removed all unneeded comments
- [x] I've updated the snapshot tests and checked to make sure they're accurate if they changed
- [x] I've removed all unnecessary `console.log`s

2021-06-12 00:55 UTC, CatQueenCodes commented
Testing - can't confirm a fix

Tried on:
-iphone7
-iPhoneSE
-iPhone11
-iPadMini
-Galaxy a51
-Huwaei P30

- JOIN button screen it is not full screen on any device

- code/name screen is not full screen on iphones but is on all other devices

-from  You've Joined The Lobby Screen forward it is not full screen on iPad or iPhone. (works on all androids)

![Code_Name](https://user-images.githubusercontent.com/59713017/121760148-e8b2ef00-caee-11eb-8780-5b934be41847.jpg)
![game_play](https://user-images.githubusercontent.com/59713017/121760149-e94b8580-caee-11eb-9f74-5777a3b7b887.jpg)
![join_screen](https://user-images.githubusercontent.com/59713017/121760150-e94b8580-caee-11eb-9fac-6b3a2aa05a56.jpg)
![Joined_Lobby](https://user-images.githubusercontent.com/59713017/121760151-e9e41c00-caee-11eb-8f6f-effef405a802.jpg)

2021-06-12 01:23 UTC, CatQueenCodes commented
Notes from call with bender after last comment above:

![image0-3](https://user-images.githubusercontent.com/59713017/121760875-9b388100-caf2-11eb-9e3b-99466ebb1f3d.png)
iPad X does not go away
- no way for it to work on iphone
- Nice to have for desktop would be a button to go in and out of fullscreen because once you're out of it you can't get back into full screen

2021-06-12 02:58 UTC, I3uckwheat commented
This seems to have the noslep stuff attached, can we remove that?

2021-06-12 03:02 UTC, CatQueenCodes commented
> This seems to have the noslep stuff attached, can we remove that? 

That's all stuff for this one. It was pics of the url bar(not full screen) in different views. 

I can delete that comment with all those pics if you want though, the last comment is most relevant

2021-06-13 04:06 UTC, wise-king-sullyman requested changes
Works great, just some minor things in the tests to clean up as we discussed.

2021-06-13 04:06 UTC, wise-king-sullyman commented on frontend/src/components/HostSettingsMenu/SettingsSubComponents/ToggleFullscreen.spec.js
> +      document.fullscreenElement = null;
Are these (and the associated restores) being used here?

2021-06-13 04:06 UTC, wise-king-sullyman commented on frontend/src/components/HostSettingsMenu/SettingsSubComponents/ToggleFullscreen.spec.js
> +      document.fullscreenElement = null;
Are these (and the associated restores) being used here?

2021-06-13 04:06 UTC, wise-king-sullyman commented on frontend/src/components/HostSettingsMenu/SettingsSubComponents/ToggleFullscreen.spec.js
> +      document.fullscreenElement = null;
Are these (and the associated restores) being used here?

2021-06-13 04:06 UTC, wise-king-sullyman commented on frontend/src/components/HostSettingsMenu/SettingsSubComponents/ToggleFullscreen.spec.js
> +      document.fullscreenElement = null;
Are these (and the associated restores) being used here?

2021-06-13 04:06 UTC, wise-king-sullyman commented on frontend/src/components/HostSettingsMenu/SettingsSubComponents/ToggleFullscreen.spec.js
> +      document.fullscreenElement = null;
Are these (and the associated restores) being used here?

2021-06-13 04:06 UTC, wise-king-sullyman commented on frontend/src/components/HostSettingsMenu/SettingsSubComponents/ToggleFullscreen.spec.js
> +      document.fullscreenElement = null;
Are these (and the associated restores) being used here?

2021-06-13 04:06 UTC, wise-king-sullyman commented on frontend/src/components/HostSettingsMenu/SettingsSubComponents/ToggleFullscreen.spec.js
> +      document.fullscreenElement = null;
Are these (and the associated restores) being used here?

2021-06-13 15:12 UTC, wise-king-sullyman reviewed
One question, then once that's discussed/changed it should be good to go.

2021-06-13 15:13 UTC, wise-king-sullyman commented on backend/start.js
> +app.listen(process.env.EXPRESS_PORT, '0.0.0.0', () =>
Did you mean to leave this in? I got the feeling from your instructions this shouldn't be pushed but I could be wrong.

2021-06-13 15:18 UTC, wise-king-sullyman approved these changes
Looks great!

2021-06-13 21:22 UTC, wise-king-sullyman approved these changes

2021-06-13 21:27 UTC, wise-king-sullyman requested changes

2021-06-13 21:27 UTC, wise-king-sullyman commented on frontend/src/helpers/requestFullscreen.js
> +    docEl.msRequestFullscreen;
I would like to see no call happen if all of these return a falsy value

2021-06-13 21:27 UTC, wise-king-sullyman commented on frontend/src/helpers/requestFullscreen.spec.js
> +  });
And a test added here for all of the fullscreen requests being falsy.

2021-06-14 00:35 UTC, I3uckwheat approved these changes

2021-06-14 00:38 UTC, wise-king-sullyman approved these changes

2021-06-14 00:40 UTC, merged