Bug/334 - Frontend tests fail for BlackCard.js
I3uckwheat/cards-of-carousal pull request #335
Opened 2021-09-06 18:46 UTC by zachmmeyer

#### 0. Make sure your issue is linked:
Closes #334 

#### 1. Purpose:

Fixes frontend tests failing on BlackCard.js claiming replaceAll is not a function.

#### 2. Implementation:

Switched out replaceAll with replace using the global flag.

#### 3. Possible Issues:

Nothing from my end. Ran tests, played a game, even made sure it was reading the underscores and changed the numbers around live. It all worked.

#### 4. How to Test:

Run the tests

#### 5. Cleanup
- [X] I've added all TODOs needed
- [X] I've removed all unneeded comments
- [X] I've updated the snapshot tests and checked to make sure they're accurate if they changed
- [X] I've removed all unnecessary `console.log`s

2021-09-06 19:50 UTC, wise-king-sullyman approved these changes

2021-09-06 20:09 UTC, I3uckwheat commented
Have we figured out *why* this is happening? I suspect this is due to an old Node version or something. This isn't something we don't want to merge without knowing *why* this is happening. This code is/was working before.

2021-09-06 20:09 UTC, I3uckwheat requested changes
See comment above.

2021-09-06 20:24 UTC, zachmmeyer commented
This project is using Node version 14 LTS, which uses V8 8.4, which does not support replaceAll. It may work in the browser, but it fails when testing. It's possible the code was tested previously with Node version 15. We just need to make sure from now own we're writing testable code locally that works with node 14LTS. Thanks @I3uckwheat [Context](https://stackoverflow.com/questions/66937529/why-doesnt-nodejs-support-string-prototype-replaceall)

2021-09-08 05:14 UTC, I3uckwheat approved these changes

2021-09-09 15:23 UTC, merged