Feature/refactor player staging
I3uckwheat/cards-of-carousal pull request #337
Opened 2021-09-16 02:43 UTC by fortypercenttitanium

#### 0. Make sure your issue is linked:

Needs to be done before #333 

#### 1. Purpose:

## Refactor staging area design

#### Before:
Players connected and were add to a "staging area" array, which would be cleared at the beginning of each round.

#### After:
Players connected are given `isConnected` and `isPlaying` on their player object in the Host Context. These are used to determine dealing of cards, picking of czar, etc... and will be further used to implement reconnects.

#### 2. Implementation:

I removed the staging array and all associated tests and replaced each function that utilized it with an implementation of an object property on the player object. 

#### 3. Possible Issues:

There were a lot of tests that were edited to make this work. I added a few test cases, but I was mostly focused on fixing the tests that were already in place. We may still be missing some unit test edge cases.

#### 4. How to Test:

* Pull branch
* Review code
* Run the game and play, ensuring there are no errors in the consoles
* Try to force edge cases

#### 5. Cleanup
- [x] I've added all TODOs needed
- [x] I've removed all unneeded comments
- [x] I've updated the snapshot tests and checked to make sure they're accurate if they changed
- [x] I've removed all unnecessary `console.log`s

2021-09-16 03:01 UTC, I3uckwheat requested changes
I haven't had a chance to pull and run this, but most of this looks pretty good outside of the `isPlaying` issue that I mentioned.

2021-09-19 21:05 UTC, wise-king-sullyman requested changes
Awesome work, I know how much of a pain this must've been!

Apologies for some of the line locations where I requested additional tests being less than helpful, unfortunately since GitHub doesn't let me add comments to lines too far away from changes I couldn't always put them where they would make the most sense.

2021-09-21 18:26 UTC, fortypercenttitanium commented on frontend/src/contexts/HostContext/HostReducer.spec.js
>                { pack: 0, text: 'test' },
> I'd also like to see a test added to ensure that the `players` object still includes non-active players.

See test suite 'PLAYER_DISCONNECTED' , first test. If you're looking for something different, let me know!

2021-09-21 18:33 UTC, fortypercenttitanium commented on frontend/src/screens/HostPregameScreen/HostPregameScreen.js
> +  const { lobbyID, playerIDs } = state;
> We need to enforce that the game can't be started with only disconnected players, I just tested and this causes a crash. Suggest replacing `playerIDs` with only players with `status: 'staging'` and also adding a test to ensure this requirement is met/functioning.

Very nice catch.

2021-09-23 02:19 UTC, wise-king-sullyman submitted a review, later dismissed

2021-11-11 00:35 UTC, I3uckwheat requested changes
2 smallllll things, otherwise, great work on this large project!

2021-11-11 00:35 UTC, I3uckwheat commented on frontend/src/contexts/HostContext/HostReducer.js
> +        state.players[id].status === 'staging',
We could use a `.includes` here to clean this up:

`['playing', 'staging'].includes(state.players[id].status`

2021-11-11 00:35 UTC, I3uckwheat commented on frontend/src/contexts/HostContext/HostReducer.js
> +        state.players[id].status === 'staging',
We could use a .includes here to clean this up:

`['playing', 'staging'].includes(state.players[id].status`

2021-11-17 03:38 UTC, I3uckwheat approved these changes

2021-11-17 04:01 UTC, wise-king-sullyman approved these changes

2021-11-17 04:02 UTC, merged